import type { FC } from "react";

import { TimeLine, TimelineItem } from "../shared/TimeLine";

const timelineItems: TimelineItem[] = [
  {
    period: "Aug 2024 - Current",
    location: "Klimra",
    header: "Co-Founder & CTO",
    description:
      "Klimra simplifies compensation for delayed train journeys in Sweden and offers an on-demand free taxi solution for short-distance delays. The company is part of the SSE Business Lab incubator. I own the technical direction and lead the engineering team.",
    listItems: [
      "Lead a team of six engineers and interns, with responsibility for hiring, mentoring, and engineering practices.",
      "Own product and technical roadmap from MVP to production, including architecture, security, and scalability.",
      "Designed and implemented a serverless backend on AWS using Lambda, DynamoDB, API Gateway, S3, Cognito, CloudFront, and Fargate.",
      "Established infrastructure as code with Terraform, automated CI/CD, and multi-environment deployment.",
      "Ensured compliance with Google CASA security requirements and strong handling of sensitive customer data.",
      "Built the core ticket analysis pipeline using OpenAI models to extract and validate train ticket details for compensation.",
      "Defined and implemented the security architecture for handling sensitive travel and payment data, including encryption, access control, and audit logging (Google CASA).",
      "Designed and shipped an AI-driven ticket analysis pipeline using OpenAI models to extract, validate, and classify train tickets end-to-end.",
    ],
    tags: [
      "AWS CloudFormation",
      "Stripe (Software)",
      "Serverless Framework",
      "Infrastructure as code (IaC)",
      "API Development",
      "Startup Development",
      "CI/CD",
      "Identity Federation",
      "AWS Fargate",
      "Product Management",
      "Google Authentication",
      "Amazon CloudWatch",
      "ESLint",
      "DevOps",
      "Amazon DynamoDB",
      "Entrepreneurship",
      "Team Leadership",
      "Serverless Architecture",
      "TypeScript",
      "Amazon Cognito",
      "Full-Stack Development",
      "Terraform",
      "Mentoring",
      "Python",
      "AWS Lambda",
      "Amazon Web Services (AWS)",
      "Cloud Computing",
      "Amazon Route 53",
      "Amazon CloudFront",
    ],
    link: "https://klimra.com",
    linkDisplay: "klimra.com",
  },
  {
    period: "Feb 2023 - Current",
    location: "Scatterin",
    header: "Full Stack Developer",
    description:
      "Early engineer at a research spin-off building a cloud platform for analysis of neutron and synchrotron experiments. Responsible for large parts of the AWS architecture and developer tooling.",
    listItems: [
      "Built and maintained a 10+ service AWS infrastructure using Terraform with S3, DynamoDB, clusters, and Lambda across multiple stages.",
      "Created 100+ AWS Lambda endpoints, ensuring scalability for large-scale data processing.",
      "Designed a custom frontend for managing large datasets, enabling users to interact with 100s gigabytes of data.",
      "Built a system for real-time analysis of neutron and synchrotron experiments, enabling users to set parameters and perform analyses as data was collected during the experiments.",
      "Collaborated with data scientists to deploy their algorithms efficiently in the cloud, improving data interaction and export workflows.",
      "Solved infrastructure challenges and optimized platform performance with AWS support.",
    ],
    tags: [
      "React.js",
      "Python (Programming Language)",
      "AWS CloudFormation",
      "Serverless Framework",
      "Infrastructure as code (IaC)",
      "API Development",
      "Microservices",
      "Data Storage",
      "Amazon S3",
      "CI/CD",
      "Software as a Service (SaaS)",
      "AWS Fargate",
      "Product Management",
      "Amazon CloudWatch",
      "ESLint",
      "Docker",
      "DevOps",
      "Amazon DynamoDB",
      "Tailwind CSS",
      "Serverless Architecture",
      "TypeScript",
      "Amazon Cognito",
      "Full-Stack Development",
      "Terraform",
      "Containers",
      "Solution Architecture",
      "AWS Lambda",
      "Amazon Web Services (AWS)",
      "Cloud Computing",
      "Serverless Computing",
      "Redux.js",
    ],
    link: "https://scatterin.com",
    linkDisplay: "scatterin.com",
  },
  {
    period: "Dec 2020 - Sep 2024",
    location: "PKTraffic, LLC",
    header: "Co-Founder & CTO",
    description:
      "PK Traffic specializes in comprehensive public record searches of traffic-related data and events, providing expert analysis and support for enhanced roadway safety and incident management. I was responsible for the end-to-end development of the company's flagship product, focusing on cost-effective, scalable solutions for traffic data collection and analysis:",
    listItems: [
      "Developed an innovative hybrid system for the integration and capture of surveillance footage across 3,000 highway cameras.",
      "Designed and implemented a scalable video storage solution that handled 10s of terabytes of traffic footage, leveraging AWS S3 Deep Glacier Archive to minimize long-term storage costs.",
      "Successfully recorded video data from approximately 45,000 traffic incidents, contributing to robust analytics.",
      "Delivered comprehensive data that enhanced quality control measures and helped police investigations.",
    ],
    tags: [
      "Python (Programming Language)",
      "AWS CloudFormation",
      "Serverless Framework",
      "API Development",
      "Data Storage",
      "Startup Development",
      "Data Engineering",
      "Amazon S3",
      "CI/CD",
      "Product Management",
      "Data Analytics",
      "Amazon CloudWatch",
      "DevOps",
      "Amazon DynamoDB",
      "Entrepreneurship",
      "Amazon EC2",
      "TypeScript",
      "Amazon Cognito",
      "SQL",
      "Full-Stack Development",
      "Extract, Transform, Load (ETL)",
      "Solution Architecture",
      "AWS Lambda",
      "Amazon Web Services (AWS)",
      "Amazon Relational Database Service (RDS)",
      "Cloud Computing",
      "Serverless Computing",
      "Redux.js",
    ],
    link: "https://pktraffic.com",
    linkDisplay: "pktraffic.com",
  },
  {
    period: "Jan 2023 - Jun 2023",
    location: "Amaceit",
    header: "Bachelor Thesis",
    description:
      'I completed a thesis titled "Cloud Computing Pricing and Deployment Efforts" investigating the landscape of public and private cloud computing services. The thesis aimed to compare the pricing and implementation efforts of various cloud providers, with a specific focus on Google GCP, Microsoft Azure, and Amazon AWS.',
    tags: [
      "Serverless Framework",
      "API Development",
      "Full-Stack Development",
      "Serverless Computing",
      "Redux.js",
    ],
    link: "https://amaceit.se",
    linkDisplay: "amaceit.se",
  },
  {
    period: "Jun 2022 - Aug 2022",
    location: "Northvolt",
    header: "Backend Software Engineer",
    description:
      "Built an advanced task management system for maintenance of factory machines at Northvolt.",
    listItems: [
      "Developed GraphQL endpoints using Go",
      "Worked on data modeling in DynamoDB",
      "Implemented Infrastructure as Code (IaC) using Terraform",
      "Developed serverless computing solutions using AWS Lambda",
    ],
    tags: [
      "Serverless Framework",
      "Infrastructure as code (IaC)",
      "API Development",
      "Microservices",
      "Databases",
      "CI/CD",
      "Data Modeling",
      "Infrastructure",
      "Product Management",
      "GraphQL",
      "Software Development",
      "Amazon DynamoDB",
      "Terraform",
      "AWS Lambda",
      "Amazon Web Services (AWS)",
      "Cloud Computing",
      "Go (Programming Language)",
    ],
    link: "https://northvolt.com",
    linkDisplay: "northvolt.com",
  },
  {
    period: "Jul 2021 - Aug 2021",
    location: "Personalstiftelsen PostNord Plus",
    header: "Full Stack Developer",
    description:
      "I worked as a software developer on a contract basis where I was responsible for developing two applications - an image editor and a mass email sender. The primary goal of these applications was to save time for the employees by automating repetitive tasks.",
    listItems: [
      "Achieved a 75% reduction in time required for image editing and email sending",
      "Used Python, PyQt, and QT Designer for development",
      "Collaborated with the team to meet business requirements",
      "Provided ongoing support and maintenance",
    ],
    tags: [
      "Python (Programming Language)",
      "Product Management",
      "Full-Stack Development",
      "PyQt",
      "Software Development",
      "Automation",
      "GUI Development",
      "QT Designer",
    ],
    link: "https://postnordplus.com",
    linkDisplay: "postnordplus.com",
  },
  {
    period: "2017 - 2020",
    location: "Personalstiftelsen PostNord Plus",
    header: "Administrative Assistant",
    description:
      "Performed administrative tasks such as handling email lists, labeling packages, and organizing events.",
    listItems: ["Developed two IT programs for the personnel foundation"],
    link: "https://postnordplus.com",
    linkDisplay: "postnordplus.com",
    hide: true,
  },
  {
    period: "2017 - 2018",
    location: "Modis Restauranger AB",
    header: "Waiter",
    description:
      "Worked as a waiter at events and handled dishwashing and serving at Restaurang Modis in Solna, Stockholm.",
    link: "https://resturangmodis.se",
    linkDisplay: "resturangmodis.se",
    hide: true,
  },
  {
    period: "Jun 2017 - Jul 2017",
    location: "Stockholm Stad",
    header: "Caretaker",
    description:
      "Worked at a daycare center for seniors, responsible for organizing small events and café activities.",
    listItems: [
      "Assisted seniors with technology, including mobile phone support",
    ],
    link: "https://jobba.stockholm",
    linkDisplay: "jobba.stockholm",
    hide: true,
  },
  {
    period: "Jun 2016 - Jul 2016",
    location: "Citroën",
    header: "Administrative Assistant",
    description:
      "Worked with administrative assignments at Citroën’s head office, including document management and office relocation.",
    link: "https://hedinbil.se",
    linkDisplay: "hedinbil.se",
    hide: true,
  },
];

export const Experience: FC = () => {
  return (
    <TimeLine
      timelineItems={timelineItems}
      title="Experience"
      id="experience"
    />
  );
};
